export const API_ENDPOINTS = {
  LOGIN: "/api/auth/login",
  REGISTER: "/api/auth/register",
  PROFILE: "/api/auth/profile",
  ADMIN_DASHBOARD: "/api/auth/admin-dashboard",
  USERS: "/api/users",
  USER_BY_ID: (id: string) => `/api/users/${id}`,
  CUSTOMERS: "/api/customers",
  CUSTOMER_BY_ID: (id: string) => `/api/customers/${id}`,
  ORDERS: "/api/orders",
  ORDER_BY_ID: (id: string) => `/api/orders/${id}`,
  VISITS: "/api/visits",
  VISIT_BY_ID: (id: string) => `/api/visits/${id}`,
  VISIT_COMPLETE: (id: string) => `/api/visits/${id}/complete`,
  VISIT_PHOTOS: (id: string) => `/api/visits/${id}/photos`,
  VISIT_SELFIE: (id: string) => `/api/visits/${id}/selfie`,
  MY_VISITS: "/api/visits/my-visits",
  PRODUCTS: "/api/products",
  PRODUCT_BY_ID: (id: string) => `/api/products/${id}`,
  // Attendance
  ATTENDANCE_CHECK_IN: "/api/attendance/check-in",
  ATTENDANCE_CHECK_OUT: "/api/attendance/check-out",
  MY_ATTENDANCE: "/api/attendance/my-attendance",
  TODAY_ATTENDANCE: "/api/attendance/today",
  ATTENDANCE_HISTORY: "/api/attendance/history",
  START_BREAK: "/api/attendance/start-break",
  END_BREAK: "/api/attendance/end-break",
};
